App\Entity\User:
    type: entity
    repositoryClass: App\Repository\UserRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        email:
            type: string
            length: 180
            nullable: false
        roles:
            type: json
            nullable: false
        password:
            type: string
            nullable: false
